name: Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: List Files
        run: ls

      - name: Print Working Directory
        run: pwd

      - name: List Files in ClientApp
        run: ls ClientApp

      - name: Install Dependencies
        run: |
            cd ClientApp
            npm install

      - name: Run Client Tests
        run: |
            cd ClientApp
            npm test

      - name: Run Unit Tests
        run: |
            cd Server/Tests
            dotnet test
